import { describe, expect, it } from 'vitest'
import { ChordEngine, KEY_DOTS } from '@/lib/chord'
import { buildPattern } from '@/lib/haptics'
import { ALERTS, pulseCount, pulseWidths } from '@/lib/alerts'
import { dotsToUnicode, textToBraille, brailleToText } from '@/lib/braille'
import { pickVoice } from '@/lib/speech'

describe('chord engine',()=>{it('supports step-mode h and sequential cells',()=>{expect(brailleToText([[1,2,5]],'en')).toBe('h');expect(brailleToText([[1],[1,2]],'en')).toBe('ab')});it('supports pointer cancel without a cell',()=>{const e=new ChordEngine();e.down(1,1);e.down(2,2);e.cancel(1);e.cancel(2);expect(e.up(1)).toBeNull();expect(e.up(2)).toBeNull()});it('commits F+D+K as one cell',()=>{const e=new ChordEngine();e.down(1,1);e.down(2,2);e.down(3,5);expect(e.up(2)).toBeNull();expect(e.up(1)).toBeNull();expect(e.up(3)).toEqual([1,2,5])});it('releases in any order',()=>{const e=new ChordEngine();[1,2,3].forEach((id)=>e.down(id,id));[3,1,2].forEach((id)=>{const out=e.up(id);if(out)expect(out).toEqual([1,2,3])})});it('separates cells and cancels safely',()=>{const e=new ChordEngine();e.down(1,1);expect(e.up(1)).toEqual([1]);e.down(2,2);expect(e.up(2)).toEqual([2]);e.down(3,1);e.cancel(3);expect(e.up(3)).toBeNull()});it('ignores repeat pointer ids',()=>{const e=new ChordEngine();e.down(1,1);e.down(1,2);expect(e.up(1)).toEqual([1])})})
describe('braille',()=>{it('maps keyboard dots and anchors',()=>{expect(KEY_DOTS).toEqual({KeyF:1,KeyD:2,KeyS:3,KeyJ:4,KeyK:5,KeyL:6});expect(textToBraille('hello','en').cells.map(dotsToUnicode).join('')).toBe('⠓⠑⠇⠇⠕');expect(textToBraille('h','en').cells[0]).toEqual([1,2,5]);expect(textToBraille(',','en').cells[0]).toEqual([2]);expect(brailleToText([[1,2,5]],'en')).toBe('h')})})
describe('haptics and alerts',()=>{it('alternates pattern and preserves total duration',()=>{const p=buildPattern([[1,3]],'normal');expect(p.length).toBeGreaterThan(1);expect(p.reduce((a,b)=>a+b,0)).toBe(900)});it('has expected pulse counts and proportional widths',()=>{expect(pulseCount(ALERTS.doorbell.pattern)).toBe(2);expect(pulseCount(ALERTS.fire.pattern)).toBe(4);expect(pulseCount(ALERTS.calling.pattern)).toBe(3);expect(pulseCount(ALERTS.horn.pattern)).toBe(1);expect(pulseWidths(ALERTS.horn.pattern)[0].ratio).toBeCloseTo(700/1100)})})
describe('voice selection',()=>{const voice=(lang:string,name=lang)=>({lang,name} as SpeechSynthesisVoice);it('selects exact, prefix, then English',()=>{expect(pickVoice([voice('en-US'),voice('hi-IN','Hindi')],'hi-IN')?.name).toBe('Hindi');expect(pickVoice([voice('hi-IN','Hindi')],'hi-IN')?.name).toBe('Hindi');expect(pickVoice([voice('en-US','English')],'ta-IN')?.name).toBe('English')})})
